HPCC-34163 code generator not included in coverage
commonSetup.cmake:
- When the Platform build for coverage add definition of '_COVERAGE' into the
  environment (using later in eclcc.cpp)

eclcc.cpp:
- Use the '_COVERAGE' to replace '_exit(*)' with 'exit(*)'.
  The '_exit()' drops everything and prevent to call all clean-up and coverage
  related functions (like update .gcda files) and that causes nearly zero
  coverage.
- This change can cause test failure like this:
  637. Test: regex_arg_types.ecl
  eclccserver: (0,0): Error C9999: eclcc exited - could be because out of
  memory - see compile log for details

Tested in local coverage build and metrics generation.

Signed-off-by: Attila Vamos <attila.vamos@gmail.com>